---
  - name: copy ssh keys from local to remote
    copy: src=~/.ssh/{{ item }} dest=/home/vagrant/.ssh owner=vagrant
    with_items:
      - id_rsa
      - id_rsa.pub

  - name: copy gitconfig from local to remote
    copy: src=~/.gitconfig dest=/home/vagrant owner=vagrant

  - name: copy dotfiles from local to remote
    copy: src=~/{{ item }} dest=/home/vagrant/ owner=vagrant
    with_items: 
      - .tmx
      - .gitignore
      - .ackrc
      - .bashrc
      - .bash_profile
      - .tmux.conf
      - .vimrc
      - .gemrc

  - name: symbolic link configs from dotfiles
    file: src=/home/master/dotfiles/{{ item }} dest=/home/vagrant/.{{ item }} state=link
    with_items: 
      - bash
      - vim
